### ISSUE TITLE
Complete new course outline

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/git-novice#1]
For Samvera workshop, we will run the following outline of "episodes":

- [x] [Introduction](https://github.com/ucsdlib/git-novice/issues/14)
- [x] [Setup](https://github.com/ucsdlib/git-novice/issues/12)
- [x] Automated Version Control
- [x] [Setting Up Git](https://github.com/ucsdlib/git-novice/issues/13)
- [x] ~[Creating a Repository](https://github.com/ucsdlib/git-novice/issues/15)~
- [x] [Tracking Changes](https://github.com/ucsdlib/git-novice/issues/16)
- [x] [Exploring History](https://github.com/ucsdlib/git-novice/issues/17)
- [x] [Ignoring Things](https://github.com/ucsdlib/git-novice/issues/18)
- [x] [Branching & Merging](https://github.com/ucsdlib/git-novice/issues/19)
- [x] [Remotes](https://github.com/ucsdlib/git-novice/issues/21)
- [x] [Collaborating](https://github.com/ucsdlib/git-novice/issues/22)
- [x] [Tools](#24)
- [x] [Conflicts](#23)

**Comment by dunn** [comment]
It can just be Remotes, since we don't want to imply that GH is the only place they can push to.

**Comment by chrissyrissmeyer** [comment]
Hooray, all the episodes are updated!
