### ISSUE TITLE
Setting Up Git

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/git-novice#13]
https://ucsdlib.github.io/git-novice/02-setup/

TODO:
This generally looks fine to me, perhaps we just remove the Dracula nonsense and replace with <your-name-here>, <your-email-address-here>, etc.?

Also should add a note about setting `autocrlf` depending on OS.

**Comment by chrissyrissmeyer** [comment]
Changed Dracula references. Did not  note about setting `autocrlf` depending on OS.

**Comment by dunn** [comment]
Partly addressed by https://github.com/ucsdlib/git-novice/pull/27
