### ISSUE TITLE
Creating a Repository

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/git-novice#15]
https://ucsdlib.github.io/git-novice/03-create/

TODO: update with new context. consider how this fits in with the notion of cloning a sample data repo.

**Comment by dunn** [comment]
Partly addressed by https://github.com/ucsdlib/git-novice/pull/27

**Comment by dunn** [comment]
Will be further addressed by https://github.com/ucsdlib/git-novice/pull/10

**Comment by mcritchlow** [comment]
Closing this as it was removed via #31
