### ISSUE TITLE
Ignoring Things

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/git-novice#18]
https://ucsdlib.github.io/git-novice/05-ignore/

TODO:
* bring the examples into context
* delete or ignore the lower sections that get into other things

I think the goal here is to just introduce the `.gitignore` file, and show how to add a file to it. Maybe a directory too. The rest seems not necessary. We can just mention that if you need something ignored in your repository, there's a way to do it.

**Comment by mcritchlow** [comment]
My vote for this one is to essentially leave it as-is. It's not related to our sample data at all, and lives alone nicely. I think in terms of time spent on it during the workshop, I'd say we just hit the first few items and then move on, but then it's there for students as a reference.

@dunn, @chrissyrissmeyer - how does that sound?

**Comment by dunn** [comment]
Yeah, I guess that's alright.

**Comment by dunn** [comment]
Is there anything left to do for this ticket then?

**Comment by mcritchlow** [comment]
Nope I think this is done
