### ISSUE TITLE
Add branching episode

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/git-novice#2]
We will be adding an episode on branching. We'll need to cover:

1. What branching is
2. How to branch
3. How branching fits in with a larger strategy/workflow of using Git/Github
4. ... (fancy images/gifs)

**Comment by chrissyrissmeyer** [comment]
I am going to work on creating some fancy images/gifs

**Comment by chrissyrissmeyer** [comment]
Branching graphics without and without head pointer are here:

- [branching with head pointer](https://docs.google.com/presentation/d/1XRzK-2KQTQJV1t3_nCBJsehJuwCcykj5rTybFCb96hc/edit#slide=id.g28e5686155_0_21)
- [branching without](https://docs.google.com/presentation/d/1j6uHvYF36BUqwO4NpzR7EBH6q7cmCz2Ba2gq7hKbj_0/edit#slide=id.g28e5686155_0_21)

We can modify, turn into animated gif, or whatever once the content is developed.

**Comment by chrissyrissmeyer** [comment]
https://github.com/ucsdlib/git-novice/pull/36
