### ISSUE TITLE
Remotes

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/git-novice#21]
https://ucsdlib.github.io/git-novice/06-remotes/

Should just need context updates. The overall narrative seems pretty solid.

**Comment by mcritchlow** [comment]
Thoughts on whether it's worth updating all the screenshots in this episode? I can see doing the screenshots, but perhaps not the diagrams. Or, leaving as-is. I'm happy to take this one for tomorrow, but would like your thoughts before doing so @dunn @chrissyrissmeyer

**Comment by dunn** [comment]
I wonder if we can get away with just removing the screenshots and walking through the process in real-time.  It's straightforward enough that students probably won't need to go back and reference it (and if they do, we can link to the GitHub docs).

**Comment by mcritchlow** [comment]
I'm totally in favor of that. In reality when I've done this that's exactly
what's happened.

**Comment by mcritchlow** [comment]
@chrissyrissmeyer if you're good with that approach, i'll get that done this morning.

**Comment by chrissyrissmeyer** [comment]
Totally fine by me!

**Comment by mcritchlow** [comment]
So here are some links I think would be valuable to replace the existing page with:

* https://help.github.com/articles/create-a-repo/
* https://help.github.com/articles/adding-an-existing-project-to-github-using-the-command-line/

Maybe an "Extra" for Github Desktop? Could also go in Tools.
* https://guides.github.com/introduction/getting-your-project-on-github/

Are there others you all know of or would recommend?
