### ISSUE TITLE
Tools

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/git-novice#24]
I believe we just want to highlight some non-terminal options, like GitKraken here. Probably also a time-permitting thing?

**Comment by dunn** [comment]
do u have time to hear the good word about magit

**Comment by mcritchlow** [comment]
I'm sure metadata librarians would love to see a little Emacs magic from you :)

**Comment by chrissyrissmeyer** [comment]
i included magit in the list of free tools ;)

https://github.com/ucsdlib/git-novice/pull/40
