### ISSUE TITLE
Version Control with Git: Intro

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/git-novice#44]
https://ucsdlib.github.io/git-novice/

Teams are not the only ones to benefit from version control: individuals can also benefit immensely. Keeping a record of what was changed, when, and why is extremely useful for any person if they ever need to come back to the project later on (e.g., a year later, when memory has faded). It can also be helpful when creating formal project documentation following the conclusion of a project, or when planning similar projects in the future.

Version control is the lab notebook of the digital world: it’s what professionals use to keep track of what they’ve done and to collaborate with other people. Every large software development project relies on it, and most programmers use it for their small jobs as well. And it isn’t just for software: books, papers, documentation, metadata, and anything that changes over time or needs to be shared can and should be stored in a version control system.

I wonder if we can collapse some of this.

**Comment by dunn** [comment]
Almost definitely.

**Comment by dunn** [comment]
Just cut the whole section paragraph IMO.
