### ISSUE TITLE
Setup: 7-Zip

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/git-novice#45]
Windows machines may have 7-Zip installed.

* Maybe make a note that folks should choose that and then "Extract here"
* Also document extract option that doesn't create a nested directory

**Comment by dunn** [comment]
It might be easier for students to tell them to just extract it using whatever way is most familiar, and if it's a nested directory so be it; we can just have them `cd` into it.

**Comment by mcritchlow** [comment]
Sounds good to me
