### ISSUE TITLE
Setting Up Git: Windows copy/paste

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/git-novice#47]
Copy and paste in the windows terminal seems to require a mouse. Let's document this since this is not something ppl are familiar with.

**Comment by mcritchlow** [comment]
I'd like to wait to write anything about this until @dunn has a chanc to run through #68

**Comment by chrissyrissmeyer** [comment]
@dunn: can you please test copy/paste in windows environment?

**Comment by dunn** [comment]
You can copy text by highlighting it then right-clicking.  `Ctrl-v` should work to paste, but you can also right-click and select 'Paste' from the context menu.

**Comment by chrissyrissmeyer** [comment]
I added a note about this to the slides, but have not added it anywhere in the episodes.

**Comment by dunn** [comment]
Which part of the slides?

**Comment by chrissyrissmeyer** [comment]
Slide 12 (Setting up Git) just as a verbal note. I figured this is the point where Windows users would most likely start wanting to copy & paste. Since in a couple of slides they will probably copy and paste the editor command at the very least.

**Comment by dunn** [comment]
Do you think it's worth adding to the episodes?

**Comment by chrissyrissmeyer** [comment]
go for it!

**Comment by dunn** [comment]
I'm not sure where would be most natural.  If they're reading the episodes on their own time, it's something they'll either know or can look up, too.

**Comment by chrissyrissmeyer** [comment]
I think if you want to add it anywhere, the [setting up git](https://ucsdlib.github.io/git-novice/02-setup/) page makes the most sense.  e.g.,  "Catsy also has to set her favorite text editor, following this table (if you are on a Windows computer you'll need to right click to copy/paste):"

But I think it is fine to skip it as well. 

Would that section of the slides be a good place to mention the arrow up and tabs? Or are we already mentioning elsewhere?

**Comment by dunn** [comment]
I don't think we are; so yes!
