### ISSUE TITLE
Setting up Git: git config

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/git-novice#48]
Don't actually need `-h` or `--help`, though it's fine

**Comment by mcritchlow** [comment]
Meh, not worth it.

**Comment by dunn** [comment]
Relatedly, should we suggest `git help <verb>` instead of `git <verb> --help`?

**Comment by mcritchlow** [comment]
Yeah, we probably should, good call. And maybe even preface it with some text saying that if you don't remember the name of the verb/command, just type `git help` and take it from there. I worry about overwhelming people with this kinda stuff..
