### ISSUE TITLE
create instructor script

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/git-novice#53]
This is typically how things are done in the Software Carpentry courses. We didn't do that in the practice run, and we have multiple instructors. So worth talking about.

**Comment by chrissyrissmeyer** [comment]
I like the idea of running through the class in a terminal window, and have a Google slide deck for images, etc.

**Comment by chrissyrissmeyer** [comment]
it would also be great to have an instructor script with the commands that participants must follow along with in order to have all needed commits for later episodes

**Comment by mcritchlow** [comment]
Yeah, we could maybe re-use the ones I used in my lessons:

https://github.com/ucsdlib/libcarp-data-notes/blob/master/lecture-notes/lc-git-notes.md

**Comment by dunn** [comment]
I think we should definitely have a live terminal.

**Comment by mcritchlow** [comment]
going to rename this to reflect creating a set of notes and base it off of the version I linked to above that Alex and I had already started hacking on a while back. I'll try and get a first draft up for you all to look at tomorrow at some point.

**Comment by mcritchlow** [comment]
I may commandeer this page https://github.com/ucsdlib/git-novice/blob/gh-pages/_extras/guide.md Seems like the best existing place to put a script for us.
