### ISSUE TITLE
discuss: remove all terminal editor examples?

### ISSUE THREAD

**Issue by chrissyrissmeyer** [ucsdlib/git-novice#58]
For this audience does it make sense to replace these instructions with a more generic "make these changes in your editor of choice"?

**Comment by dunn** [comment]
Yeah, I think so.

**Comment by mcritchlow** [comment]
I'll do a first pass at this now.

**Comment by mcritchlow** [comment]
Related, I'm going to remove the `cat`'s too, since not everyone is going to have this.
