### ISSUE TITLE
check example messages

### ISSUE THREAD

**Issue by chrissyrissmeyer** [ucsdlib/git-novice#59]
We want to make sure that our example messages match participant output throughout (to our best extent possible).

**Comment by dunn** [comment]
Which ones don't?

**Comment by chrissyrissmeyer** [comment]
I wasn't able to catch which ones didn't match up. I was planning on running through the whole course once all the updates were done to check, and will also double check the commands we need to issue at that time.

**Comment by dunn** [comment]
https://github.com/ucsdlib/git-novice/pull/99
