### ISSUE TITLE
change order of introductory materials

### ISSUE THREAD

**Issue by chrissyrissmeyer** [ucsdlib/git-novice#60]
Does it make sense to talk about what version control is, then introduce the scenarios, and then download the practice files?

**Comment by chrissyrissmeyer** [comment]
we maybe should even cut the narrative piece: https://ucsdlib.github.io/git-novice/

**Comment by mcritchlow** [comment]
I could see removing the Catsy parts of the narrative, though I think we could also just not read it and leave it as a reference point for people to give context.

As for order, yeah I think that might be a good approach. So are you thinking something like?

1. Automated Version Control
2. (Talk about the context/use case, not necessarily a "section")
3. Setup
4. Setting Up Git
5. Creating a repository...
....

Another option is we put Setting Up Git immediately after we talk about what version control is, and then have them download the files and move ahead. So something like:

1. Automated Version Control
2. Setting Up Git
3. (Talk about the context/use case, not necessarily a "section")
4. Setup
5. Creating a repository..
...

**Comment by chrissyrissmeyer** [comment]
Could we ask them to do the Setup portion (download and unzip files) before the workshop?

**Comment by mcritchlow** [comment]
As long as we lock down the content, yeah we definitely could!

**Comment by chrissyrissmeyer** [comment]
Okay, so my plan is to combine the intro, context/use case, and Automated Version Control into one "section" in the slide deck, followed by Setting Up Git and Creating a Repository. I don't think we need to update any of the website pages because that text works in that environment (it was just awkward when presenting). We already sent everyone the Setup instructions, and I have a note in the housekeeping section to ask everyone if they have everything downloaded and installed. How does that sound @mcritchlow and @dunn? 

If good, I will close this issue.

**Comment by dunn** [comment]
Yeah, I think that makes sense.
