### ISSUE TITLE
revisit images used in the pages

### ISSUE THREAD

**Issue by chrissyrissmeyer** [ucsdlib/git-novice#61]
some of them are weird

chrissy might be able to replace them with less weird ones if that is helpful

**Comment by dunn** [comment]
This one in particular can go away https://ucsdlib.github.io/git-novice/fig/git_staging.svg

**Comment by dunn** [comment]
Are there any others that need to go?

**Comment by chrissyrissmeyer** [comment]
IMO that one was the worst offender. But, if we do this again, I might want to update some more -- just not sure we have the bandwidth to make more new ones now.
