### ISSUE TITLE
discuss: make file changes during branching not merging?

### ISSUE THREAD

**Issue by chrissyrissmeyer** [ucsdlib/git-novice#65]
Should we have participants make the changes used in merging during branching?

**Comment by mcritchlow** [comment]
I defer to @dunn , though I think that could potentially work nicely. Ties the two section together, 'full clrcle', and all that.

**Comment by dunn** [comment]
I think we should combine them into a single section.

**Comment by chrissyrissmeyer** [comment]
https://github.com/ucsdlib/git-novice/pull/78
