### ISSUE TITLE
create further resources section

### ISSUE THREAD

**Issue by chrissyrissmeyer** [ucsdlib/git-novice#66]
for more information

**Comment by dunn** [comment]
from our google doc
- https://eev.ee/blog/2015/04/24/just-enough-git-to-be-less-dangerous/
- https://git-scm.com/book/en/v2

**Comment by chrissyrissmeyer** [comment]
@dunn what do you think about adding those here? https://ucsdlib.github.io/git-novice/reference/

**Comment by dunn** [comment]
Would we want a new subsection for more in-depth documentation?

**Comment by chrissyrissmeyer** [comment]
I'd be fine with that as well. I could see adding links to the Lynda.com training, and other training resources too.
