### ISSUE TITLE
create outline for part 2

### ISSUE THREAD

**Issue by chrissyrissmeyer** [ucsdlib/git-novice#67]

**Comment by chrissyrissmeyer** [comment]
@dunn and @mcritchlow : https://docs.google.com/presentation/d/1y_ND3kTllGoXcf0Ympvdtson9SAYIB2hgUp9vsPPYCc/edit#slide=id.g2992f34447_0_0

Look good to you?

**Comment by dunn** [comment]
'Benefits' seems vague relative to the others.  Maybe something like 'Benefits of Version Control and Automation'?

**Comment by chrissyrissmeyer** [comment]
@dunn What do you think about "Benefits: Technical and Otherwise"? If you check out the slide notes, most of the benefits that are currently there are more "otherwise" (Closer collaboration with developers, Empowerment, More control to metadata librarians)

**Comment by chrissyrissmeyer** [comment]
Also, these are clearly the benefits from my perspective. You and Matt should feel free to add in the benefits from your perspective -- technical and otherwise.

**Comment by dunn** [comment]
Yeah, that works.
