### ISSUE TITLE
Ignoring Things: replace examples with a single example using cats-as-data repo

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/git-novice#73]
Simplify things by replacing the existing example with a simple addition of a file we don't want to track in our cats-as-data repo. Then we'll create a gitignore file, add the filename to it, and make a commit. Everything else in the section will get ripped out.

**Comment by mcritchlow** [comment]
Wondering if we should include an empty .gitignore file and a file to ignore in the cats-as-data repo so there's less setup for people. Then it would just be:

- git status (see that git sees the file)
- open the .gitignore file
- add the name of the file to ignore
- git status (see that git ignores the file)
- add/commit

Thoughts?

**Comment by dunn** [comment]
@mcritchlow sounds good

**Comment by mcritchlow** [comment]
Closed via #81
