### ISSUE TITLE
decision: when to add/commit the csv

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/git-novice#76]
We missed this yesterday because it's buried at the bottom in the "Committing Multiple Files". So we need to either:

- Make sure we cover this section (we didn't yesterday)
- Bring it higher up in the section (say when we include images, or whatever)
- Add it to the beginning of the branching section
- ...
 
Thoughts?

**Comment by chrissyrissmeyer** [comment]
I'd vote for bringing it higher up in the section. Maybe they could do an add all?

**Comment by mcritchlow** [comment]
Yeah I think combining adding the `images` directory and the csv at the same time would work well.

**Comment by mcritchlow** [comment]
Though if we do pre-populate an empty .gitignore and file to ignore (see #73) then we couldn't do an add all. But we could still add both in one go.

**Comment by dunn** [comment]
Why couldn't we do the ignore piece after this?

**Comment by dunn** [comment]
IIRC `git commit -a` only stages changes to already-tracked files.  We'd have to do something like `git add .`

**Comment by dunn** [comment]
Or is that what you meant @chrissyrissmeyer ?

**Comment by chrissyrissmeyer** [comment]
I meant `git add -A` (which I use all the time). At least according to [this thread](https://stackoverflow.com/questions/572549/difference-between-git-add-a-and-git-add), it is slightly different than `git add .`.

But maybe this could just be added as a tip or something in the section where we introduce `git add`.

**Comment by dunn** [comment]
Oh, I forgot about `add -A`.  That would be less confusing too, I think.

I'm happy using it in the lesson, or just having it as a tip.

**Comment by mcritchlow** [comment]
> Why couldn't we do the ignore piece after this?


Right, we would. My concern with an `add -A` or `add .` is including the `.gitignore` and `cats-human-situations.md` files in the repo that are used in the Ignore section. At the moment at least, that section is assuming the files aren't tracked by git (yet).

**Comment by dunn** [comment]
Oh right right.  Maybe I meant 'before'? I'm tired.

**Comment by chrissyrissmeyer** [comment]
Maybe in that case, we just include `add -A` or `add .` somewhere as tips? I don't want you to have to update the ignore section. 

And I suspect most of the audience would use a GUI in the future, so maybe saving them from typing is not a big concern.

**Comment by mcritchlow** [comment]
Yeah as tips would be great 👍

**Comment by dunn** [comment]
What's the status on this? Have we added it one way or another, early enough that it won't be missed?

**Comment by dunn** [comment]
Not yet: https://ucsdlib.github.io/git-novice/03-changes/
