### ISSUE TITLE
decision: who's laptop are we presenting with?

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/git-novice#98]
Partially this is a heads up. I've got through and added all the commits to my own cats-as-data repo and added you both as collaborators. https://github.com/mcritchlow/cats-as-data

My thinking is with whoever's laptop/github account we're using, I'm assuming one of yours, I'll commandeer during the collaborating episode to demonstrate acting as the Owner (creating a repo using your account and adding a collaborator) and Collaborator (will clone from my cats repo and make local changes, a PR, etc.)

I think this will work out. Worst case we have lots of pictures already and we can walk people through it :)

**Comment by chrissyrissmeyer** [comment]
i'm cool with us using my laptop if that works for both of you (bonus: my track pad is set up to scroll in the "traditional" way, not the new fangled "natural" way... and now I sound like an old cranky person). also makes sense since i will need to demo gitkraken

**Comment by dunn** [comment]
You can unfix my mouse scroll when it's your turn to present, and I have the VPN set up too.
